SSDLITE:
  ratios: [[2.0, 3.0],
          [2.0, 3.0],
          [2.0, 3.0],
          [2.0, 3.0],
          [2.0],
          [2.0]]
  scales: [0.2, 0.325, 0.45, 0.575, 0.7, 0.825, 0.95]
  fm_sizes: [19, 10, 5, 3, 2, 1]
  image_size: 300